SELECT P.PRODUCT_ID, IFNULL(ROUND(SUM(P.PRICE*S.UNITS)/SUM(S.UNITS),2),0) AS AVERAGE_PRICE
FROM PRICES P LEFT JOIN UNITSSOLD S ON P.PRODUCT_ID=S.PRODUCT_ID AND S.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID
ORDER BY P.PRODUCT_ID, AVERAGE_PRICE  ASC